package com.alibaba.ctoo.opensource.domain.repository.mapper;

import com.alibaba.ctoo.opensource.domain.repository.dataobject.ArticleVersionDO;
import com.alibaba.ctoo.opensource.domain.repository.dataobject.ArticleVersionParam;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author zhuangjiaju
 */
@Mapper
public interface ArticleVersionMapper {
    /**
     * 根据WHERE条件COUNT
     * @param articleVersionParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(ArticleVersionParam articleVersionParam);

    /**
     * 插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(ArticleVersionDO record);

    /**
     * 根据字段选择性插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(ArticleVersionDO record);

    /**
     * 根据WHERE条件查询，返回不包含长文本字段
     * @param articleVersionParam
     * @return
     *
     * @mbg.generated
     */
    List<ArticleVersionDO> selectByParam(ArticleVersionParam articleVersionParam);

    /**
     * 根据主键查询
     * @param id
     * @return
     *
     * @mbg.generated
     */
    ArticleVersionDO selectByPrimaryKey(Long id);

    /**
     * 根据WHERE条件选择性更新
     * @param record
     * @param articleVersionParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") ArticleVersionDO record, @Param("articleVersionParam") ArticleVersionParam articleVersionParam);

    /**
     * 根据WHERE条件更新，不更新长文本字段
     * @param record
     * @param articleVersionParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") ArticleVersionDO record, @Param("articleVersionParam") ArticleVersionParam articleVersionParam);

    /**
     * 根据主键选择性更新
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArticleVersionDO record);

    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArticleVersionDO record);

    /**
     * 批量插入
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<ArticleVersionDO> records);
}