package com.alibaba.ctoo.opensource.domain.repository.mapper;

import com.alibaba.ctoo.opensource.domain.repository.dataobject.AuthSourceDO;
import com.alibaba.ctoo.opensource.domain.repository.dataobject.AuthSourceParam;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author qiuyuyu
 */
@Mapper
public interface AuthSourceMapper {
    /**
     * 根据WHERE条件COUNT
     * @param authSourceParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(AuthSourceParam authSourceParam);

    /**
     * 根据WHERE条件删除
     * @param authSourceParam
     * @return
     *
     * @mbg.generated
     */
    int deleteByParam(AuthSourceParam authSourceParam);

    /**
     * 根据主键删除
     * @param id
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * 插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(AuthSourceDO record);

    /**
     * 根据字段选择性插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(AuthSourceDO record);

    /**
     * 根据WHERE条件查询，返回不包含长文本字段
     * @param authSourceParam
     * @return
     *
     * @mbg.generated
     */
    List<AuthSourceDO> selectByParam(AuthSourceParam authSourceParam);

    /**
     * 根据主键查询
     * @param id
     * @return
     *
     * @mbg.generated
     */
    AuthSourceDO selectByPrimaryKey(Long id);

    /**
     * 根据WHERE条件选择性更新
     * @param record
     * @param authSourceParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") AuthSourceDO record, @Param("authSourceParam") AuthSourceParam authSourceParam);

    /**
     * 根据WHERE条件更新，不更新长文本字段
     * @param record
     * @param authSourceParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") AuthSourceDO record, @Param("authSourceParam") AuthSourceParam authSourceParam);

    /**
     * 根据主键选择性更新
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthSourceDO record);

    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthSourceDO record);

    /**
     * 批量插入
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<AuthSourceDO> records);
}