package com.alibaba.ctoo.opensource.domain.repository.mapper;

import com.alibaba.ctoo.opensource.domain.repository.dataobject.OperationBannerDO;
import com.alibaba.ctoo.opensource.domain.repository.dataobject.OperationBannerParam;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author zhuangjiaju
 */
@Mapper
public interface OperationBannerMapper {
    /**
     * 根据WHERE条件COUNT
     * @param operationBannerParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(OperationBannerParam operationBannerParam);

    /**
     * 插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(OperationBannerDO record);

    /**
     * 根据字段选择性插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(OperationBannerDO record);

    /**
     * 根据WHERE条件查询，返回不包含长文本字段
     * @param operationBannerParam
     * @return
     *
     * @mbg.generated
     */
    List<OperationBannerDO> selectByParam(OperationBannerParam operationBannerParam);

    /**
     * 根据主键查询
     * @param id
     * @return
     *
     * @mbg.generated
     */
    OperationBannerDO selectByPrimaryKey(Long id);

    /**
     * 根据WHERE条件选择性更新
     * @param record
     * @param operationBannerParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") OperationBannerDO record, @Param("operationBannerParam") OperationBannerParam operationBannerParam);

    /**
     * 根据WHERE条件更新，不更新长文本字段
     * @param record
     * @param operationBannerParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") OperationBannerDO record, @Param("operationBannerParam") OperationBannerParam operationBannerParam);

    /**
     * 根据主键选择性更新
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OperationBannerDO record);

    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OperationBannerDO record);

    /**
     * 批量插入
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<OperationBannerDO> records);
}