package com.alibaba.ctoo.opensource.domain.repository.mapper;

import com.alibaba.ctoo.opensource.domain.repository.dataobject.ProjectHistoryDO;
import com.alibaba.ctoo.opensource.domain.repository.dataobject.ProjectHistoryParam;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author liugong
 */
@Mapper
public interface ProjectHistoryMapper {
    /**
     * 根据WHERE条件COUNT
     * @param projectHistoryParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(ProjectHistoryParam projectHistoryParam);

    /**
     * 插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(ProjectHistoryDO record);

    /**
     * 根据字段选择性插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(ProjectHistoryDO record);

    /**
     * 根据WHERE条件查询，返回不包含长文本字段
     * @param projectHistoryParam
     * @return
     *
     * @mbg.generated
     */
    List<ProjectHistoryDO> selectByParam(ProjectHistoryParam projectHistoryParam);

    /**
     * 根据主键查询
     * @param id
     * @return
     *
     * @mbg.generated
     */
    ProjectHistoryDO selectByPrimaryKey(Long id);

    /**
     * 根据WHERE条件选择性更新
     * @param record
     * @param projectHistoryParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") ProjectHistoryDO record, @Param("projectHistoryParam") ProjectHistoryParam projectHistoryParam);

    /**
     * 根据WHERE条件更新，不更新长文本字段
     * @param record
     * @param projectHistoryParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") ProjectHistoryDO record, @Param("projectHistoryParam") ProjectHistoryParam projectHistoryParam);

    /**
     * 根据主键选择性更新
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProjectHistoryDO record);

    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProjectHistoryDO record);

    /**
     * 批量插入
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<ProjectHistoryDO> records);
}