package com.alibaba.ctoo.opensource.domain.repository.mapper;

import com.alibaba.ctoo.opensource.domain.repository.dataobject.ProjectDocumentDO;
import com.alibaba.ctoo.opensource.domain.repository.dataobject.ProjectDocumentParam;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author zhuangjiaju
 */
@Mapper
public interface ProjectDocumentMapper {
    /**
     * 根据WHERE条件COUNT
     * @param projectDocumentParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(ProjectDocumentParam projectDocumentParam);

    /**
     * 插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(ProjectDocumentDO record);

    /**
     * 根据字段选择性插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(ProjectDocumentDO record);

    /**
     * 根据WHERE条件查询，返回不包含长文本字段
     * @param projectDocumentParam
     * @return
     *
     * @mbg.generated
     */
    List<ProjectDocumentDO> selectByParam(ProjectDocumentParam projectDocumentParam);

    /**
     * 根据主键查询
     * @param id
     * @return
     *
     * @mbg.generated
     */
    ProjectDocumentDO selectByPrimaryKey(Long id);

    /**
     * 根据WHERE条件选择性更新
     * @param record
     * @param projectDocumentParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") ProjectDocumentDO record, @Param("projectDocumentParam") ProjectDocumentParam projectDocumentParam);

    /**
     * 根据WHERE条件更新，不更新长文本字段
     * @param record
     * @param projectDocumentParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") ProjectDocumentDO record, @Param("projectDocumentParam") ProjectDocumentParam projectDocumentParam);

    /**
     * 根据主键选择性更新
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProjectDocumentDO record);

    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProjectDocumentDO record);

    /**
     * 批量插入
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<ProjectDocumentDO> records);
}