package com.alibaba.ctoo.opensource.domain.repository.mapper;

import java.util.List;

import com.alibaba.ctoo.opensource.domain.repository.dataobject.ProjectGeneralStatisticDO;
import com.alibaba.ctoo.opensource.domain.repository.dataobject.ProjectGeneralStatisticParam;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author liugong
 */
@Mapper
public interface ProjectGeneralStatisticMapper {
    /**
     * 根据WHERE条件COUNT
     * @param projectGeneralStatisticParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(ProjectGeneralStatisticParam projectGeneralStatisticParam);

    /**
     * 插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(ProjectGeneralStatisticDO record);

    /**
     * 根据字段选择性插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(ProjectGeneralStatisticDO record);

    /**
     * 根据WHERE条件查询，返回不包含长文本字段
     * @param projectGeneralStatisticParam
     * @return
     *
     * @mbg.generated
     */
    List<ProjectGeneralStatisticDO> selectByParam(ProjectGeneralStatisticParam projectGeneralStatisticParam);

    /**
     * 根据主键查询
     * @param id
     * @return
     *
     * @mbg.generated
     */
    ProjectGeneralStatisticDO selectByPrimaryKey(Long id);

    /**
     * 根据WHERE条件选择性更新
     * @param record
     * @param projectGeneralStatisticParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") ProjectGeneralStatisticDO record, @Param("projectGeneralStatisticParam") ProjectGeneralStatisticParam projectGeneralStatisticParam);

    /**
     * 根据WHERE条件更新，不更新长文本字段
     * @param record
     * @param projectGeneralStatisticParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") ProjectGeneralStatisticDO record, @Param("projectGeneralStatisticParam") ProjectGeneralStatisticParam projectGeneralStatisticParam);

    /**
     * 根据主键选择性更新
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProjectGeneralStatisticDO record);

    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProjectGeneralStatisticDO record);

    /**
     * 批量插入
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<ProjectGeneralStatisticDO> records);
}