package com.alibaba.ctoo.opensource.domain.repository.mapper;

import com.alibaba.ctoo.opensource.domain.repository.dataobject.ProjectTagDO;
import com.alibaba.ctoo.opensource.domain.repository.dataobject.ProjectTagParam;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author zhuangjiaju
 */
@Mapper
public interface ProjectTagMapper {
    /**
     * 根据WHERE条件COUNT
     * @param projectTagParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(ProjectTagParam projectTagParam);

    /**
     * 插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(ProjectTagDO record);

    /**
     * 根据字段选择性插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(ProjectTagDO record);

    /**
     * 根据WHERE条件查询，返回不包含长文本字段
     * @param projectTagParam
     * @return
     *
     * @mbg.generated
     */
    List<ProjectTagDO> selectByParam(ProjectTagParam projectTagParam);

    /**
     * 根据主键查询
     * @param id
     * @return
     *
     * @mbg.generated
     */
    ProjectTagDO selectByPrimaryKey(Long id);

    /**
     * 根据WHERE条件选择性更新
     * @param record
     * @param projectTagParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") ProjectTagDO record, @Param("projectTagParam") ProjectTagParam projectTagParam);

    /**
     * 根据WHERE条件更新，不更新长文本字段
     * @param record
     * @param projectTagParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") ProjectTagDO record, @Param("projectTagParam") ProjectTagParam projectTagParam);

    /**
     * 根据主键选择性更新
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProjectTagDO record);

    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProjectTagDO record);

    /**
     * 批量插入
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<ProjectTagDO> records);
}