package com.alibaba.ctoo.opensource.domain.repository.mapper;

import com.alibaba.ctoo.opensource.domain.repository.dataobject.ProjectDocumentDomainDO;
import com.alibaba.ctoo.opensource.domain.repository.dataobject.ProjectDocumentDomainParam;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author zhuangjiaju
 */
@Mapper
public interface ProjectDocumentDomainMapper {
    /**
     * 根据WHERE条件COUNT
     * @param projectDocumentDomainParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(ProjectDocumentDomainParam projectDocumentDomainParam);

    /**
     * 插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(ProjectDocumentDomainDO record);

    /**
     * 根据字段选择性插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(ProjectDocumentDomainDO record);

    /**
     * 根据WHERE条件查询，返回不包含长文本字段
     * @param projectDocumentDomainParam
     * @return
     *
     * @mbg.generated
     */
    List<ProjectDocumentDomainDO> selectByParam(ProjectDocumentDomainParam projectDocumentDomainParam);

    /**
     * 根据主键查询
     * @param id
     * @return
     *
     * @mbg.generated
     */
    ProjectDocumentDomainDO selectByPrimaryKey(Long id);

    /**
     * 根据WHERE条件选择性更新
     * @param record
     * @param projectDocumentDomainParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") ProjectDocumentDomainDO record, @Param("projectDocumentDomainParam") ProjectDocumentDomainParam projectDocumentDomainParam);

    /**
     * 根据WHERE条件更新，不更新长文本字段
     * @param record
     * @param projectDocumentDomainParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") ProjectDocumentDomainDO record, @Param("projectDocumentDomainParam") ProjectDocumentDomainParam projectDocumentDomainParam);

    /**
     * 根据主键选择性更新
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProjectDocumentDomainDO record);

    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProjectDocumentDomainDO record);

    /**
     * 批量插入
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<ProjectDocumentDomainDO> records);
}