package com.alibaba.ctoo.opensource.domain.repository.mapper;

import com.alibaba.ctoo.opensource.domain.repository.dataobject.RequestLogDO;
import com.alibaba.ctoo.opensource.domain.repository.dataobject.RequestLogParam;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author zhuangjiaju
 */
@Mapper
public interface RequestLogMapper {
    /**
     * 根据WHERE条件COUNT
     * @param requestLogParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(RequestLogParam requestLogParam);

    /**
     * 插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(RequestLogDO record);

    /**
     * 根据字段选择性插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(RequestLogDO record);

    /**
     * 根据WHERE条件查询，返回包含长文本字段
     * @param requestLogParam
     * @return
     *
     * @mbg.generated
     */
    List<RequestLogDO> selectByParamWithBLOBs(RequestLogParam requestLogParam);

    /**
     * 根据WHERE条件查询，返回不包含长文本字段
     * @param requestLogParam
     * @return
     *
     * @mbg.generated
     */
    List<RequestLogDO> selectByParam(RequestLogParam requestLogParam);

    /**
     * 根据主键查询
     * @param id
     * @return
     *
     * @mbg.generated
     */
    RequestLogDO selectByPrimaryKey(Long id);

    /**
     * 根据WHERE条件选择性更新
     * @param record
     * @param requestLogParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") RequestLogDO record, @Param("requestLogParam") RequestLogParam requestLogParam);

    /**
     * 根据WHERE条件更新，更新长文本字段
     * @param record
     * @param requestLogParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamWithBLOBs(@Param("record") RequestLogDO record, @Param("requestLogParam") RequestLogParam requestLogParam);

    /**
     * 根据WHERE条件更新，不更新长文本字段
     * @param record
     * @param requestLogParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") RequestLogDO record, @Param("requestLogParam") RequestLogParam requestLogParam);

    /**
     * 根据主键选择性更新
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RequestLogDO record);

    /**
     * 根据主键更新，更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(RequestLogDO record);

    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RequestLogDO record);

    /**
     * 批量插入
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<RequestLogDO> records);
}