package com.alibaba.ctoo.opensource.domain.repository.mapper;

import com.alibaba.ctoo.opensource.domain.repository.dataobject.TagDO;
import com.alibaba.ctoo.opensource.domain.repository.dataobject.TagParam;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author zhuangjiaju
 */
@Mapper
public interface TagMapper {
    /**
     * 根据WHERE条件COUNT
     * @param tagParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(TagParam tagParam);

    /**
     * 插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(TagDO record);

    /**
     * 根据字段选择性插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(TagDO record);

    /**
     * 根据WHERE条件查询，返回不包含长文本字段
     * @param tagParam
     * @return
     *
     * @mbg.generated
     */
    List<TagDO> selectByParam(TagParam tagParam);

    /**
     * 根据主键查询
     * @param id
     * @return
     *
     * @mbg.generated
     */
    TagDO selectByPrimaryKey(Long id);

    /**
     * 根据WHERE条件选择性更新
     * @param record
     * @param tagParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") TagDO record, @Param("tagParam") TagParam tagParam);

    /**
     * 根据WHERE条件更新，不更新长文本字段
     * @param record
     * @param tagParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") TagDO record, @Param("tagParam") TagParam tagParam);

    /**
     * 根据主键选择性更新
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TagDO record);

    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TagDO record);

    /**
     * 批量插入
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<TagDO> records);
}