package com.alibaba.ctoo.opensource.domain.repository.mapper;

import com.alibaba.ctoo.opensource.domain.repository.dataobject.UserRoleDO;
import com.alibaba.ctoo.opensource.domain.repository.dataobject.UserRoleParam;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author qiuyuyu
 */
@Mapper
public interface UserRoleMapper {
    /**
     * 根据WHERE条件COUNT
     * @param userRoleParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(UserRoleParam userRoleParam);

    /**
     * 根据WHERE条件删除
     * @param userRoleParam
     * @return
     *
     * @mbg.generated
     */
    int deleteByParam(UserRoleParam userRoleParam);

    /**
     * 根据主键删除
     * @param id
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * 插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(UserRoleDO record);

    /**
     * 根据字段选择性插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(UserRoleDO record);

    /**
     * 根据WHERE条件查询，返回不包含长文本字段
     * @param userRoleParam
     * @return
     *
     * @mbg.generated
     */
    List<UserRoleDO> selectByParam(UserRoleParam userRoleParam);

    /**
     * 根据主键查询
     * @param id
     * @return
     *
     * @mbg.generated
     */
    UserRoleDO selectByPrimaryKey(Long id);

    /**
     * 根据WHERE条件选择性更新
     * @param record
     * @param userRoleParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") UserRoleDO record, @Param("userRoleParam") UserRoleParam userRoleParam);

    /**
     * 根据WHERE条件更新，不更新长文本字段
     * @param record
     * @param userRoleParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") UserRoleDO record, @Param("userRoleParam") UserRoleParam userRoleParam);

    /**
     * 根据主键选择性更新
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserRoleDO record);

    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserRoleDO record);

    /**
     * 批量插入
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<UserRoleDO> records);
}